[helpers]

[default]
depends = []

[default.files]

[vim.files]
vimrc = { target="~/.vimrc", type="symbolic" }
gvimrc = { target="~/.gvimrc", type="symbolic" }
vim = { target="~/.vim", type="symbolic" }

[bash.files]
bashrc = "~/.bashrc"
inputrc = "~/.inputrc"

[neovim.files]
"config/nvim" = { target="~/.config/nvim", type="symbolic" }

[alacritty.files]
# see (windows|linux).toml
"config/alacritty/windows.yml" = ""
"config/alacritty/linux.yml" = ""

[wezterm.files]
"config/wezterm" = "~/.config/wezterm"

[x.files]
Xresources = "~/.Xresources"

[git.files]
gitconfig = "~/.gitconfig"

[winget.files]
# see windows.toml
"winget.json" = ""

[byobu.files]
byobu = "~/.byobu"

[mise.files]
"config/mise" = "~/.config/mise"

[default.variables]
