packages = ["vim", "bash", "neovim", "alacritty", "wezterm", "git", "wsl"]

[files]
"config/nvim" = "~/AppData/Local/nvim"
"config/wezterm" = "~/.config/wezterm"
"config/alacritty/windows.yml" = "~/AppData/Roaming/alacritty/alacritty.yml"
